### ISSUE TITLE
Check Push Notification Permissions

### ISSUE THREAD

**Issue by wickeym** [OneSignal/OneSignal-Corona-Example#3]
Is there a way to check if push is currently enabled in Corona SDK? 
Like there is here:
[iOS native SDK](https://documentation.onesignal.com/docs/ios-native-sdk#section--getpermissionsubscriptionstate-)

Sincerely,
Michael Wickey

**Comment by jkasten2** [comment]
@wickeym You can call `OneSignal.IdsAvailableCallback` and check if a pushToken in the callback to know if the user has accepted push notifications.
https://documentation.onesignal.com/docs/corona-sdk#section-ids-available-callback
